import type { Post } from './types'

const baseUrl = import.meta.env.BASE_URL

export const posts: Post[] = [
  {
    postId: 'FE-SCALE-011',
    title: 'Typography leads the interface',
    postType: 'single-image',
    aspectRatio: '1:1',
    theme: 'dark',
    status: 'published',
    tags: ['typography', 'hierarchy'],
    createdAt: '2025-01-15T10:00:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-01_1x1_master.jpeg`,
      alt: 'Monospace typography sample showing code and design alignment',
    },
    summary: 'Layout follows reading, not decoration. Type scale creates hierarchy.',
  },
  {
    postId: 'DS-012',
    title: 'Color is structural',
    postType: 'single-image',
    aspectRatio: '4:5',
    theme: 'light',
    status: 'published',
    tags: ['color', 'system'],
    createdAt: '2025-01-14T14:30:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-02_4x5_master.jpeg`,
      alt: 'Color palette extracted from urban and natural photography studies',
    },
    summary: 'Accent is reserved for intent and focus.',
  },
  {
    postId: 'UXSYS-013',
    title: 'Photography is context, not content',
    postType: 'carousel',
    aspectRatio: '1:1',
    theme: 'dark',
    status: 'ready',
    tags: ['photography', 'layout'],
    createdAt: '2025-01-13T09:15:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-02_1x1_master.jpeg`,
      alt: 'Subdued photography informing layout decisions without competing for attention',
    },
    summary: 'It informs decisions without demanding attention.',
  },
  {
    postId: 'INT-014',
    title: 'Minimal scrolling by design',
    postType: 'single-image',
    aspectRatio: '1:1',
    theme: 'dark',
    status: 'published',
    tags: ['interaction', 'navigation'],
    createdAt: '2025-01-12T16:45:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-01_3x2_1_master.jpeg`,
      alt: 'Interaction-driven exploration with click and reveal patterns',
    },
    summary: 'Exploration happens through interaction.',
  },
  {
    postId: 'SYS-015',
    title: 'This is not a design system',
    postType: 'single-image',
    aspectRatio: '4:5',
    theme: 'light',
    status: 'published',
    tags: ['system', 'constraints'],
    createdAt: '2025-01-11T11:20:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-02_2x3_master.jpeg`,
      alt: 'Controlled starting point with deliberate constraints and intentional boundaries',
    },
    summary: 'It is a controlled starting point.',
  },
  {
    postId: 'VID-016',
    title: 'Design-in-code exploration',
    postType: 'video',
    aspectRatio: '16:9',
    theme: 'dark',
    status: 'draft',
    tags: ['code', 'design'],
    createdAt: '2025-01-10T13:00:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-03_3x2_master.jpeg`,
      alt: 'Visual systems translated into product decisions through code',
    },
    summary: 'Photographic inputs inform color, rhythm, and emotional context.',
  },
  {
    postId: 'DOC-017',
    title: 'Layout rhythm and constraints',
    postType: 'document',
    aspectRatio: '1:1',
    theme: 'light',
    status: 'ready',
    tags: ['layout', 'rhythm'],
    createdAt: '2025-01-09T08:30:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-02_3x2_1_master.jpeg`,
      alt: 'Layout rhythm derived from photographic composition principles',
    },
    summary: 'Constraints resolved through implementation and iteration.',
  },
  {
    postId: 'CAR-018',
    title: 'System thinking in visual design',
    postType: 'carousel',
    aspectRatio: '1:1',
    theme: 'dark',
    status: 'published',
    tags: ['system', 'thinking'],
    createdAt: '2025-01-08T15:10:00Z',
    cover: {
      src: `${baseUrl}assets/magnific/magnific-photo-01_1x1_master.jpeg`,
      alt: 'Systems thinking applied to visual design decisions',
    },
    summary: 'Deliberate constraints. Intentional boundaries.',
  },
]

